version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - CLIENT_URL=http://frontend:5173
    networks:
      - fitbuddy-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:5000/api  # Use the backend container name
    networks:
      - fitbuddy-network

networks:
  fitbuddy-network:
    driver: bridge
