version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - mongo_url=mongodb+srv://admin:8qO8w7DhSDWGEebM@fitbudyyclstr.fkea0.mongodb.net/?retryWrites=true&w=majority&appName=fitbudyyclstr
      - JWT=fitbuddy
    restart: always

